# num2words = {0:"",1:"one",2:"two",3:"three",4:"four",5:"five"
#  ,6:"six",7:"seven",8:"eight",9:"nine",10:"ten"
#  ,11:"eleven",12:"twelve",13:"thirteen",14:"fourteen"
#  ,15:"fifteen",16:"sixteen",17:"seventeen",18:"eighteen"
#  ,19:"nineteen",20:"twenty",30:"thirty",40:"forty"
#  ,50:"fifty",60:"sixty",70:"seventy",80:"eighty"
#  ,90:"ninety",100:"hundred",1000:"onethousand"}

# s = 0

# for i in range(1001):
#     if i in num2words:
#         word = num2words[i]
#         word = word.replace(" ","")
#         # print(word)
#         # print(len(word))
#         s += len(word)
#     elif i < 100:
#         first = int(str(i)[0])*10 
#         second = int(str(i)[1])
#         word = num2words[first] +''+ num2words[second]
#         word = word.replace(" ","")
#         s += len(word)
#         # print(word)
#         # print(len(word)) 
#     elif 100<= i <= 999:
#         first = num2words[int(str(i)[0])] + "hundredand" 
#         second = int(str(i)[1]) * 10
#         third = int(str(i)[2])
        
#         if (second+third) in num2words:
#             second = num2words[second + third]
#             # print(first + second)
#             word = first + second
#             word = word.replace(" ","")
#             # print(len(word))
#             s += len(word)
#         else:
#             second = num2words[int(str(i)[1]) * 10]
#             third = num2words[int(str(i)[2])]
#             # print(first + second +""+third)
#             word = first + second +""+third
#             word = word.replace(" ","")
#             s += len(word)
#             # print(len(word))

# print(s)
# 21145 wrongly generated by the above code !!!!!!
# right Answer is 21124 THE BELOW CODE IS THE RIGHT ONE!!!!!!!!
# WHY I LEFT 2 CODES FOR THE SAME PROBLEM IS TO SHOW HOW I STRUGGLED TO GET THE RIGHT ANSWER!!!!
# THANKS TO GOD AND DEEPSEEK !
num2words = {
    0: "", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
    6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten",
    11: "eleven", 12: "twelve", 13: "thirteen", 14: "fourteen",
    15: "fifteen", 16: "sixteen", 17: "seventeen", 18: "eighteen",
    19: "nineteen", 20: "twenty", 30: "thirty", 40: "forty",
    50: "fifty", 60: "sixty", 70: "seventy", 80: "eighty",
    90: "ninety", 100: "hundred", 1000: "thousand"
}

s = 0

for i in range(1, 1001):  # Start from 1 to include 1000
    if i in num2words:
        if i == 100:
            word = "one" + num2words[100]  # "onehundred"
        elif i == 1000:
            word = "one" + num2words[1000]  # "onethousand"
        else:
            word = num2words[i]
        word = word.replace(" ", "").replace("-", "")
        s += len(word)
    elif i < 100:
        first = int(str(i)[0]) * 10
        second = int(str(i)[1])
        word = num2words[first] + num2words[second]
        word = word.replace(" ", "").replace("-", "")
        s += len(word)
    elif 100 <= i <= 999:
        first = num2words[int(str(i)[0])] + num2words[100]  # e.g., "onehundred"
        remainder = i % 100
        if remainder == 0:
            word = first  # No "and" for multiples of 100
        else:
            if remainder in num2words:
                word = first + "and" + num2words[remainder]  # e.g., "onehundredandone"
            else:
                second = num2words[int(str(remainder)[0]) * 10]
                third = num2words[int(str(remainder)[1])]
                word = first + "and" + second + third  # e.g., "onehundredandtwentyone"
        word = word.replace(" ", "").replace("-", "")
        s += len(word)

print(s)